export const ERROR_GIF = "ERROR_GIF"
export const RECEIVE_GIF = "RECEIVE_GIF"

export const EMAIL_CHANGED = "EMAIL_CHANGED"
export const PASSWORD_CHANGED = "PASSWORD_CHANGED"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"
export const LOGIN_USER = "LOGIN_USER"
