// flow-typed signature: 52924e21d8b019255ad141b04e69aaa6
// flow-typed version: <<STUB>>/rc-swipeout_v^1.2.5/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-swipeout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-swipeout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-swipeout/lib/index' {
  declare module.exports: any;
}

declare module 'rc-swipeout/lib/index.web' {
  declare module.exports: any;
}

declare module 'rc-swipeout/lib/Swipeout' {
  declare module.exports: any;
}

declare module 'rc-swipeout/lib/Swipeout.web' {
  declare module.exports: any;
}

declare module 'rc-swipeout/lib/util/splitObject' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-swipeout/lib/index.js' {
  declare module.exports: $Exports<'rc-swipeout/lib/index'>;
}
declare module 'rc-swipeout/lib/index.web.js' {
  declare module.exports: $Exports<'rc-swipeout/lib/index.web'>;
}
declare module 'rc-swipeout/lib/Swipeout.js' {
  declare module.exports: $Exports<'rc-swipeout/lib/Swipeout'>;
}
declare module 'rc-swipeout/lib/Swipeout.web.js' {
  declare module.exports: $Exports<'rc-swipeout/lib/Swipeout.web'>;
}
declare module 'rc-swipeout/lib/util/splitObject.js' {
  declare module.exports: $Exports<'rc-swipeout/lib/util/splitObject'>;
}
